export const PROMPT_LIMITS = {
  MAX_THINKING_LENGTH: 2000,
  MAX_CODE_LENGTH: 5000,
  MAX_WHITELIST_LENGTH: 2000,
  MAX_PROBLEM_CONTENT_SUMMARY: 500,
  SNIPPET_CONTEXT_RADIUS: 32,
} as const;

export const API_DEFAULTS = {
  DEFAULT_TEMPERATURE: 0.7,
  MAX_COMPLETION_TOKENS: 4096,
  FETCH_MODELS_TIMEOUT_MS: 15000,
  CHAT_ENDPOINT: '/chat/completions',
  MODELS_ENDPOINT: '/models',
  STREAM_CHUNK_TIMEOUT_MS: 30000,
  SSE_KEEPALIVE_INTERVAL_MS: 15000,
} as const;

export const QUERY_DEFAULTS = {
  DEFAULT_PAGE_LIMIT: 50,
  MAX_PAGINATION_LIMIT: 100,
} as const;
